"""
Notifications route: project-scoped notification feed.

Notifications are generated by real pipeline events (see
services/notification_service.py); this route only exposes them.
"""

import logging
from typing import List, Optional
from uuid import UUID
from datetime import datetime, timezone

from fastapi import APIRouter, Query, HTTPException, status, Depends

from backend.models.schemas import NotificationOut, MarkAllReadResponse, CurrentUser
from backend.db.supabase_client import get_supabase_client
from backend.db.errors import PersistenceError, execute_read, execute_write
from backend.auth.security import require_any_authenticated, require_project_access
from backend.auth.rate_limiter import rate_limit_api

router = APIRouter(prefix="", tags=["Notifications"], dependencies=[Depends(rate_limit_api)])
logger = logging.getLogger("onground.notifications")


@router.get("/notifications", response_model=List[NotificationOut])
async def list_notifications(
    project_id: UUID = Query(..., description="Project to read notifications for"),
    unread_only: bool = Query(False, description="Only return unread notifications"),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    current_user: CurrentUser = Depends(require_any_authenticated),
):
    """List notifications for a project the user is a member of."""
    require_project_access(current_user, project_id)

    supabase = get_supabase_client()
    if not supabase:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database is not configured.",
        )

    query = (
        supabase.table("notifications")
        .select("*")
        .eq("project_id", str(project_id))
        .or_(f"user_id.eq.{current_user.id},user_id.is.null")
        .order("created_at", desc=True)
        .range(offset, offset + limit - 1)
    )

    if unread_only:
        query = query.is_("read_at", "null")

    try:
        rows = execute_read(query, table="notifications", operation="notifications.list")
    except PersistenceError as exc:
        logger.error("Failed to list notifications: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=exc.public_detail,
        ) from exc

    return [NotificationOut(**row) for row in rows]


@router.post("/notifications/{notification_id}/read", response_model=NotificationOut)
async def mark_read(
    notification_id: UUID,
    current_user: CurrentUser = Depends(require_any_authenticated),
):
    """Mark a single notification as read."""
    supabase = get_supabase_client()
    if not supabase:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database is not configured.",
        )

    try:
        rows = execute_read(
            supabase.table("notifications")
            .select("*")
            .eq("id", str(notification_id))
            .limit(1),
            table="notifications",
            operation="notifications.load",
        )
    except PersistenceError as exc:
        logger.error("Failed to load notification %s: %s", notification_id, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=exc.public_detail,
        ) from exc

    if not rows:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Notification '{notification_id}' not found",
        )

    notification = rows[0]
    require_project_access(current_user, notification["project_id"])

    now = datetime.now(timezone.utc).isoformat()
    try:
        updated = execute_write(
            supabase.table("notifications")
            .update({"read_at": now})
            .eq("id", str(notification_id))
            .select("*"),
            table="notifications",
            operation="notifications.mark_read",
        )
    except PersistenceError as exc:
        logger.error("Failed to mark notification %s read: %s", notification_id, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=exc.public_detail,
        ) from exc

    return NotificationOut(**updated[0])


@router.post("/notifications/read-all", response_model=MarkAllReadResponse)
async def mark_all_read(
    project_id: UUID = Query(..., description="Project to mark notifications for"),
    current_user: CurrentUser = Depends(require_any_authenticated),
):
    """Mark all notifications for a project as read for the current user."""
    require_project_access(current_user, project_id)

    supabase = get_supabase_client()
    if not supabase:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Database is not configured.",
        )

    now = datetime.now(timezone.utc).isoformat()
    try:
        result = execute_write(
            supabase.table("notifications")
            .update({"read_at": now})
            .eq("project_id", str(project_id))
            .or_(f"user_id.eq.{current_user.id},user_id.is.null")
            .is_("read_at", "null")
            .select("id"),
            table="notifications",
            operation="notifications.mark_all_read",
            expect_rows=False,
        )
    except PersistenceError as exc:
        logger.error("Failed to mark all notifications read: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=exc.public_detail,
        ) from exc

    return MarkAllReadResponse(marked=len(result))
