"""
Pydantic schemas and validation models for OnGround.
"""

from typing import Optional, List, Dict, Any
from uuid import UUID
from datetime import datetime, date
from pydantic import BaseModel, Field, field_validator


# =============================================================================
# Common & Health Schemas
# =============================================================================

class HealthResponse(BaseModel):
    status: str = "ok"
    version: str = "1.0.0"


class CurrentUser(BaseModel):
    id: UUID
    email: Optional[str] = None
    role: str = "supervisor"  # "planner" or "supervisor"


class ErrorResponse(BaseModel):
    error: str
    message: str
    detail: Optional[str] = None


# =============================================================================
# Upload Schemas
# =============================================================================

class UploadResponse(BaseModel):
    extraction_id: UUID
    file_url: str
    status: str = "pending"


# =============================================================================
# Extraction Schemas
# =============================================================================

class ExtractedActivityRaw(BaseModel):
    """Raw structure parsed from LLM JSON output.
    Any confidence field generated by the LLM is ignored/stripped."""
    activity_description: str
    discipline: Optional[str] = "unknown"
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    location_reference: Optional[str] = None

    @field_validator("discipline", mode="before")
    def normalize_discipline(cls, v):
        if not v or not isinstance(v, str):
            return "unknown"
        valid_disciplines = {
            "civil", "piping", "electrical", "instrumentation",
            "static_rotating_equipment", "hse"
        }
        val = v.lower().strip().replace(" ", "_")
        return val if val in valid_disciplines else "unknown"


class ExtractedActivityCreate(BaseModel):
    """Model for inserting a normalized extracted activity with server-calculated confidence."""
    extraction_id: UUID
    activity_description: str
    discipline: Optional[str] = "unknown"
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    location_reference: Optional[str] = None
    extraction_confidence: float = Field(..., ge=0.0, le=1.0)


class ExtractionResponse(BaseModel):
    extraction_id: UUID
    activities_count: int
    activities: List[Dict[str, Any]]
    status: str


# =============================================================================
# Matching Schemas
# =============================================================================

class CandidateMatch(BaseModel):
    plan_activity_id: UUID
    activity_code: str
    activity_description: str
    score: float = Field(..., ge=0.0, le=1.0)


class MatchResult(BaseModel):
    status: str  # "auto_linked", "pending_review", "unmatched"
    extracted_activity_id: UUID
    match_id: Optional[UUID] = None
    plan_activity_id: Optional[UUID] = None
    confidence_score: Optional[float] = None
    candidates: Optional[List[CandidateMatch]] = None


# =============================================================================
# Review Schemas (Confirm / Reject)
# =============================================================================

class ConfirmResponse(BaseModel):
    match_id: UUID
    status: str = "confirmed"


class RejectRequest(BaseModel):
    reason: Optional[str] = None


class RejectResponse(BaseModel):
    match_id: UUID
    status: str = "rejected"


class ReassignRequest(BaseModel):
    target_plan_activity_id: UUID
    reason: Optional[str] = None


class ReassignResponse(BaseModel):
    match_id: UUID
    plan_activity_id: UUID
    status: str = "confirmed"
    resolved_by: Optional[UUID] = None


# =============================================================================
# Read / Query Schemas (Step 5.1)
# =============================================================================


class SchedulePlanItemOut(BaseModel):
    id: UUID
    project_id: UUID
    activity_code: str
    activity_description: str
    discipline: str
    planned_start: date
    planned_end: date
    created_at: Optional[datetime] = None


class ReportItemOut(BaseModel):
    id: UUID
    project_id: UUID
    file_url: str
    file_type: Optional[str] = None
    status: str
    uploaded_by: Optional[UUID] = None
    created_at: Optional[datetime] = None


class ExtractedActivityContext(BaseModel):
    id: UUID
    activity_description: str
    discipline: Optional[str] = None
    extraction_confidence: float
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    location_reference: Optional[str] = None


class SchedulePlanContext(BaseModel):
    id: UUID
    project_id: UUID
    activity_code: str
    activity_description: str
    discipline: str
    planned_start: date
    planned_end: date


class ScheduleMatchOut(BaseModel):
    id: UUID
    extracted_activity_id: UUID
    plan_activity_id: UUID
    confidence_score: float
    status: str
    resolved_by: Optional[UUID] = None
    candidates: Optional[List[Dict[str, Any]]] = None
    created_at: Optional[datetime] = None
    extracted_activity: Optional[ExtractedActivityContext] = None
    schedule_plan: Optional[SchedulePlanContext] = None


class UnmatchedActivityOut(BaseModel):
    id: UUID
    extracted_activity_id: UUID
    best_score: Optional[float] = None
    resolution: str = "unresolved"
    created_at: Optional[datetime] = None
    extracted_activity: Optional[ExtractedActivityContext] = None


class AuditTrailOut(BaseModel):
    id: UUID
    related_match_id: Optional[UUID] = None
    related_unmatched_id: Optional[UUID] = None
    action: str
    confidence_score: Optional[float] = None
    actor: Optional[UUID] = None
    created_at: datetime


class MatchesBreakdown(BaseModel):
    auto_linked: int = 0
    pending_review: int = 0
    confirmed: int = 0
    rejected: int = 0


class UnmatchedBreakdown(BaseModel):
    unresolved: int = 0
    marked_new_activity: int = 0
    manually_linked: int = 0


class AnalyticsOut(BaseModel):
    total_planned_activities: int = 0
    total_extractions: int = 0
    total_extracted_activities: int = 0
    total_matches: int = 0
    matches_by_status: MatchesBreakdown = Field(default_factory=MatchesBreakdown)
    total_unmatched: int = 0
    unmatched_by_resolution: UnmatchedBreakdown = Field(default_factory=UnmatchedBreakdown)
    total_audit_events: int = 0
    average_match_confidence: Optional[float] = None

