"""
Pydantic schemas and validation models for TrueLine.
"""

from typing import Optional, List, Dict, Any
from uuid import UUID
from datetime import datetime, date
from pydantic import BaseModel, Field, field_validator


# =============================================================================
# Common & Health Schemas
# =============================================================================

class HealthResponse(BaseModel):
    status: str = "ok"
    version: str = "1.0.0"


class CurrentUser(BaseModel):
    id: UUID
    email: Optional[str] = None
    role: str = "supervisor"  # "planner" or "supervisor"


class ErrorResponse(BaseModel):
    error: str
    message: str
    detail: Optional[str] = None


# =============================================================================
# Upload Schemas
# =============================================================================

class UploadResponse(BaseModel):
    extraction_id: UUID
    file_url: str
    status: str = "pending"


# =============================================================================
# Extraction Schemas
# =============================================================================

class ExtractedActivityRaw(BaseModel):
    """Raw structure parsed from LLM JSON output.
    Any confidence field generated by the LLM is ignored/stripped."""
    activity_description: str
    discipline: Optional[str] = "unknown"
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    location_reference: Optional[str] = None

    @field_validator("discipline", mode="before")
    def normalize_discipline(cls, v):
        if not v or not isinstance(v, str):
            return "unknown"
        valid_disciplines = {
            "civil", "piping", "electrical", "instrumentation",
            "static_rotating_equipment", "hse"
        }
        val = v.lower().strip().replace(" ", "_")
        return val if val in valid_disciplines else "unknown"


class ExtractedActivityCreate(BaseModel):
    """Model for inserting a normalized extracted activity with server-calculated confidence."""
    extraction_id: UUID
    activity_description: str
    discipline: Optional[str] = "unknown"
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    location_reference: Optional[str] = None
    extraction_confidence: float = Field(..., ge=0.0, le=1.0)


class ExtractionResponse(BaseModel):
    extraction_id: UUID
    activities_count: int
    activities: List[Dict[str, Any]]
    status: str


# =============================================================================
# Matching Schemas
# =============================================================================

class CandidateMatch(BaseModel):
    plan_activity_id: UUID
    activity_code: str
    activity_description: str
    score: float = Field(..., ge=0.0, le=1.0)


class MatchResult(BaseModel):
    status: str  # "auto_linked", "pending_review", "unmatched"
    extracted_activity_id: UUID
    match_id: Optional[UUID] = None
    plan_activity_id: Optional[UUID] = None
    confidence_score: Optional[float] = None
    candidates: Optional[List[CandidateMatch]] = None


# =============================================================================
# Review Schemas (Confirm / Reject)
# =============================================================================

class ConfirmResponse(BaseModel):
    match_id: UUID
    status: str = "confirmed"


class RejectRequest(BaseModel):
    reason: Optional[str] = None


class RejectResponse(BaseModel):
    match_id: UUID
    status: str = "rejected"
